# Put the bot into debug mode
debug: False

# Database config settings.
database:
  user: postgres
  password: admin
  database: ritsubot
  host: localhost

# Production bot settings
main_bot:
  token: NzIxMzQ1MTUzNzE2OTc3NzE0.XuTLBg.hrVsxS1brWGsNewHK39A3jduRz8

# Lavalink server connection settings
lavalink:
  host: localhost
  port: 2333
  password: ritsu

# List of owners id
owners:
  - 446748603860516894

# Lyric finding service
ksoft:
  token: eyJ0IjogImFwcCIsICJrIjogImtobWFjc2lnIiwgInBrIjogbnVsbCwgIm8iOiAiNDQ2NzQ4NjAzODYwNTE2ODk0IiwgImMiOiAxNTMxMzU1Nn0.bad21328372647e174f02c19d4060c3ab6cda7a9b8d886fc5de51a18f20884d2
